# Generated by Django 2.1.5 on 2019-02-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sms', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=2000)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Office')),
            ],
        ),
    ]
